/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_lktk_JNI */

#ifndef _Included_io_lktk_JNI
#define _Included_io_lktk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_lktk_JNI
 * Method:    create_hasher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_lktk_JNI_create_1hasher
  (JNIEnv *, jclass);

/*
 * Class:     io_lktk_JNI
 * Method:    destroy_hasher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_lktk_JNI_destroy_1hasher
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_lktk_JNI
 * Method:    blake3_hasher_init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_lktk_JNI_blake3_1hasher_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_lktk_JNI
 * Method:    blake3_hasher_init_keyed
 * Signature: (JLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_lktk_JNI_blake3_1hasher_1init_1keyed
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_lktk_JNI
 * Method:    blake3_hasher_init_derive_key
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_lktk_JNI_blake3_1hasher_1init_1derive_1key
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_lktk_JNI
 * Method:    blake3_hasher_update
 * Signature: (JLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_io_lktk_JNI_blake3_1hasher_1update
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     io_lktk_JNI
 * Method:    blake3_hasher_finalize
 * Signature: (JLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_io_lktk_JNI_blake3_1hasher_1finalize
  (JNIEnv *, jclass, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
