/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scash_JNI */

#ifndef _Included_org_scash_JNI
#define _Included_org_scash_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scash_JNI
 * Method:    create_hasher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_scash_JNI_create_1hasher
  (JNIEnv *, jclass);

/*
 * Class:     org_scash_JNI
 * Method:    destroy_hasher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_scash_JNI_destroy_1hasher
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_scash_JNI
 * Method:    blake3_hasher_init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_scash_JNI_blake3_1hasher_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_scash_JNI
 * Method:    blake3_hasher_update
 * Signature: (JLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_scash_JNI_blake3_1hasher_1update
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_scash_JNI
 * Method:    blake3_hasher_finalize
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_scash_JNI_blake3_1hasher_1finalize
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
