/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_scash_NativeBLAKE3 */

#ifndef _Included_org_scash_NativeBLAKE3
#define _Included_org_scash_NativeBLAKE3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_scash_NativeBLAKE3
 * Method:    createHasher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_scash_NativeBLAKE3_createHasher
  (JNIEnv *, jclass);

/*
 * Class:     org_scash_NativeBLAKE3
 * Method:    destroyHasher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_scash_NativeBLAKE3_destroyHasher
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
